version: '3.0'

services:

  nginx:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/includes:/etc/nginx/includes
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./source:/var/www/html
    ports:
      - "${DOCKER_HTTP_PORT}:8080"

  php:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: "${DOCKER_PHP_VERSION}"
        USER_ID: "${DOCKER_USER_ID}"
    environment:
      XDEBUG_MODE: "off"                        # off | develop | debug
      XDEBUG_CONFIG: "client_host=172.26.0.1"   # set your docker0 address
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"       # set your server name from PhpStorm settings
    volumes:
      - ./docker/php/php.ini:/etc/php/${DOCKER_PHP_VERSION}/fpm/conf.d/99-overrides.ini
      - ./docker/php/php-cli.ini:/etc/php/${DOCKER_PHP_VERSION}/cli/conf.d/99-overrides.ini
      - ./docker/php/cron/scheduler:/etc/cron.d/scheduler
      - ./source:/var/www/html

  mariadb:
    image: mariadb:${DOCKER_MARIADB_VERSION}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MARIADB_DATABASE}
      MYSQL_USER: ${DOCKER_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_MARIADB_PASSWORD}

volumes:
  mariadb-data:
