<?php

namespace App\Filament\Components;

use Filament\Forms\Components\Checkbox;

class FormButton extends Checkbox
{
    protected string $view = 'filament.component.formButton';
    public $callback;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->registerListeners([
            'run' => [
                function (FormButton $component): void {
                    if ($component->callback) {
                        call_user_func($component->callback);
                    }
                }
            ]
        ]);
    }

    public function onClick(\Closure $closure): static
    {
        $this->callback = $closure;

        return $this;
    }
}
